site_name: MECH & Cheese Programming Documentation
# site_url: https://sites.google.com/g.comalisd.org/mechsjaegernauts/home
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.footer   # prev/next buttons
    - content.code.copy   # copy code blocks
  palette:
    - scheme: default
      primary: 'F0502A'
      accent: 'F0502A'
  language: en
  logo: images/team-name-transparent.png
  favicon: images/team-name-transparent.png

plugins:
  # - awesome-pages

nav:
  - Home: index.md
  - MK Docs:
      - Overview: mkdocs/overview.md
      - Getting Started: mkdocs/getting-started.md
      - Accessing the Team Documentation Project: mkdocs/github.md
      - Project Strucure: mkdocs/project-structure.md
      - Markdown Formatting: mkdocs/markdown-formatting.md
      - Customizing the Material Theme: mkdocs/material-theme.md
      - Writing Guidelines: mkdocs/writing-guidelines.md
      - FAQ and Troubleshooting: mkdocs/faq-troubleshooting.md
  - FRC:
      - The Basics: frc/intro.md
      - Drivetrain: frc/drivetrain.md
      - Sensors: frc/sensors.md
      - Electrical: frc/electrical.md
  - BEST:
      - Controls: best/controls.md
  - Resources: resources/links.md
