site_name: MECH & Cheese Programming Documentation
use_directory_urls: false
site_url: https://mech-and-cheese.github.io/programming-documentation/
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.footer   # prev/next buttons
    - content.code.copy   # copy code blocks
  palette:
    - scheme: default
      primary: 'F0502A'
      accent: 'F0502A'
  language: en
  logo: images/team-name-transparent.png
  favicon: images/team-name-transparent.png


markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - abbr
  - attr_list
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - MK Docs:
      - Overview: mkdocs/overview.md
      - Getting Started: mkdocs/getting-started.md
      - Accessing the Team Documentation Project: mkdocs/github.md
      - Project Strucure: mkdocs/project-structure.md
      - Markdown Formatting: mkdocs/markdown-formatting.md
      - Customizing the Material Theme: mkdocs/material-theme.md
      - Writing Guidelines: mkdocs/writing-guidelines.md
      - FAQ and Troubleshooting: mkdocs/faq-troubleshooting.md
  - FRC:
      - The Basics: frc/intro.md
      - Drivetrain: frc/drivetrain.md
      - Sensors: frc/sensors.md
      - Limelight:
          - Overview: frc/limelight/index.md
          - Concepts:
            - Control Theory: frc/limelight/concepts/control-theory.md
            - Coordinates: frc/limelight/concepts/coordinates.md
          - Implementations:
            - 2D Chassis Align: frc/limelight/implementations/chassis-align-2d.md
            - 3D Chassis Align: frc/limelight/implementations/advanced-3d.md
            - Turret Tracking: frc/limelight/implementations/turret-tracking.md
          - References:
            - Troubleshooting: frc/limelight/reference/troubleshooting.md
            - Video Library: frc/limelight/reference/video-library.md
  - BEST:
      - Controls: best/controls.md
  - Resources: resources/links.md

dev_addr: '127.0.0.1:8000'